name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Convert to html
      run: |
        npm i generate-md
        npx generate-md --layout $LAYOUT --input ./md --output ./www/doc
        cat md/dark.css >> www/doc/assets/css/style.css

    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzrO --delete
        path: www/
        remote_path: /home/hosting/data/sites/fledg.re
        remote_host: fledg.re
        remote_user: hosting
        remote_key: ${{ secrets.DEPLOY_KEY }}
